### ISSUE TITLE
Plugin in spanish

### ISSUE THREAD

**Issue by fedefabre** [ankitagarwal/moodle-block_fbcomments#7]
Hi!

I propose a simple contribution to the community

------- into blocks/fbcomments/block_fbcomments.php

Just edit this:

    protected function get_fb_js() {
        return '(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, "script", "facebook-jssdk"));';
    }

Before: js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";

------

It's a simple change in the Facebook's JS connection, that puts the plugin in spanish.
I think that is very useful for all the spanish speakers that enjoy this API and you can put both options here in github.

Thankyou for uploading this block.

**Comment by ankitagarwal** [comment]
@fedefabre 

Sorry for getting to this years later. But your suggestions are great and still valid.

I am going to integrate this feature in 3.0 of the plugin.
